// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_-vsFGmNv4ChVmPZ8HAjrD_v1PqVyqA',
    appId: '1:731566592192:web:a962b762b51d8079851d25',
    messagingSenderId: '731566592192',
    projectId: 'relive-e591f',
    authDomain: 'relive-e591f.firebaseapp.com',
    storageBucket: 'relive-e591f.firebasestorage.app',
    measurementId: 'G-YKRF4EKZPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhFIlYlJIPOuq6C-4DJJYig7-cZ8bzbg8',
    appId: '1:731566592192:android:4c7535db8e802afb851d25',
    messagingSenderId: '731566592192',
    projectId: 'relive-e591f',
    storageBucket: 'relive-e591f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxZvVp9SNsrfxZLo-G349FozaxCNQ-XE',
    appId: '1:731566592192:ios:a78b058d2762a719851d25',
    messagingSenderId: '731566592192',
    projectId: 'relive-e591f',
    storageBucket: 'relive-e591f.firebasestorage.app',
    androidClientId: '731566592192-lnh8bc32sgl0359norap592o8p01505i.apps.googleusercontent.com',
    iosClientId: '731566592192-iqlhrf4g9s3l0ssds5qss96b4ri0in88.apps.googleusercontent.com',
    iosBundleId: 'com.example.reliveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxZvVp9SNsrfxZLo-G349FozaxCNQ-XE',
    appId: '1:731566592192:ios:a78b058d2762a719851d25',
    messagingSenderId: '731566592192',
    projectId: 'relive-e591f',
    storageBucket: 'relive-e591f.firebasestorage.app',
    androidClientId: '731566592192-lnh8bc32sgl0359norap592o8p01505i.apps.googleusercontent.com',
    iosClientId: '731566592192-iqlhrf4g9s3l0ssds5qss96b4ri0in88.apps.googleusercontent.com',
    iosBundleId: 'com.example.reliveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3_-vsFGmNv4ChVmPZ8HAjrD_v1PqVyqA',
    appId: '1:731566592192:web:ae4ab9581150277e851d25',
    messagingSenderId: '731566592192',
    projectId: 'relive-e591f',
    authDomain: 'relive-e591f.firebaseapp.com',
    storageBucket: 'relive-e591f.firebasestorage.app',
    measurementId: 'G-BQKR4WL9ND',
  );

}